name: home_security_cam
description: Android home cameras and viewer with Agora RTC, plus a local PC viewer.
publish_to: 'none'
version: 1.0.1+23

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI e Icone
  cupertino_icons: ^1.0.8

  # Streaming e Camera (Agora)
  # Aggiornato alla versione 6.4.0 per pieno supporto a Flutter 3.24+
  agora_rtc_engine: ^6.4.0
  
  # Funzionalità di Sistema
  # Gestione permessi e prevenzione standby
  permission_handler: ^11.3.1
  wakelock_plus: ^1.2.8
  battery_plus: ^6.0.3
  
  crypto: ^3.0.6

  # Memoria locale
  shared_preferences: ^2.3.2
  flutter_foreground_task: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Lints aggiornati per suggerimenti di codice più moderni
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true